In [11]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification

# Generate a simple synthetic dataset
X, y = make_classification(n_samples=10, n_features=5, random_state=0)

print("Before Tranformation: ")
print(X[:2], "\n")

# Standardize the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply PCA
pca = PCA(n_components=2)  # Reduce to 2 dimensions from 5 dimensions
X_pca = pca.fit_transform(X_scaled)

# Print explained variance ratio
print(f'Explained Variance Ratio: {pca.explained_variance_ratio_}\n')

# Print the transformed data
print(f'Transformed Data (first 2 samples):\n{X_pca[:2]}')

Before Tranformation: 
[[-0.50965218 -0.14778398 -0.79249401 -0.52978546  0.29484027]
 [-0.30230275 -0.80328386 -0.51203824  1.23271508 -1.60020786]] 

Explained Variance Ratio: [0.56118031 0.23974362]

Transformed Data (first 2 samples):
[[ 0.47512209  1.76660336]
 [-1.46108546  1.17498839]]
